In [4]:
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data

In [5]:
data=pd.read_csv('/content/sample_data/mnist_train_small.csv')

In [6]:
data

6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0      5  0    0    0    0    0  ...      0      0      0      0      0      0
1      7  0    0    0    0    0  ...      0      0      0      0      0      0
2      9  0    0    0    0    0  ...      0      0      0      0      0      0
3      5  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
19994  0  0    0    0    0    0  ...      0      0      0      0      0      0
19995  1  0    0    0    0    0  ...      0      0      0      0      0      0
19996  2  0    0    0    0    0  ...      0      0      0      0      0      0
19997  9  0    0    0    0    0  ...      0      0      0      0      0      0
19998  5  0    0    0    0    0  ...      0      0      0      0      0      0

[19999 rows x 785 columns]

In [7]:
y=data.iloc[:,:1].values

In [9]:
X=data.iloc[:,1:].values

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
def find_neighbours(k, X_train, new_point):
  neighbour_arr=[]
  for i in range(len(X_train)):
    dist=np.sqrt(sum(np.square(X_train[i]-new_point))) #euclidean distance
    neighbour_arr.append([i,dist])
    neighbour_arr=sorted(neighbour_arr,key=lambda x:x[1])

  return print(np.array(neighbour_arr[0:k])), print('\n')

In [19]:
X_train.shape

(15999, 784)

In [18]:
X_test.shape

(4000, 784)

In [16]:
find_neighbours(4,X_train,X_test[45])

[[11655.          1157.041918  ]
 [12206.          1278.83462574]
 [ 5791.          1281.51589924]
 [ 5350.          1327.36581243]]




(None, None)

In [ ]:
for j in range(0,X_test.shape[0]):
  txt='For test data {} \n'
  print(txt.format(j+1))
  find_neighbours(4,X_train,X_test[j]) #in a way, finding distance of all test points from the train points

Streaming output truncated to the last 5000 lines.
[[ 5519.           985.58561272]
 [12346.          1023.51306782]
 [ 9170.          1156.85521998]
 [ 9412.          1174.06132719]]


For test data 768 

[[ 1436.          1077.38804523]
 [  653.          1117.88639852]
 [12186.          1150.27474979]
 [15899.          1160.50204653]]


For test data 769 

[[ 6479.           894.35898833]
 [ 9830.           962.76217209]
 [15952.          1024.84828145]
 [ 3138.          1147.98127162]]


For test data 770 

[[ 3567.          1167.55085542]
 [ 6002.          1261.85537999]
 [ 6062.          1277.64392536]
 [14628.          1294.36161871]]


For test data 771 

[[ 4918.          1487.53218453]
 [15349.          1626.96496582]
 [11252.          1634.20225186]
 [ 1182.          1684.36931817]]


For test data 772 

[[1654.         1017.88015012]
 [9232.         1274.85214829]
 [7349.         1284.29085491]
 [9865.         1322.74411736]]


For test data 773 

[[  630.          1215.3201