In [38]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier


In [4]:
data=pd.read_csv('/content/sample_data/mnist_train_small.csv')

In [5]:
data

6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0      5  0    0    0    0    0  ...      0      0      0      0      0      0
1      7  0    0    0    0    0  ...      0      0      0      0      0      0
2      9  0    0    0    0    0  ...      0      0      0      0      0      0
3      5  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
19994  0  0    0    0    0    0  ...      0      0      0      0      0      0
19995  1  0    0    0    0    0  ...      0      0      0      0      0      0
19996  2  0    0    0    0    0  ...      0      0      0      0      0      0
19997  9  0    0    0    0    0  ...      0      0      0      0      0      0
19998  5  0    0    0    0    0  ...      0      0      0      0      0      0

[19999 rows x 785 columns]

In [6]:
arr=np.array(data)

In [7]:
arr

array([[5, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0]])

In [8]:
y=arr[:,[0]]
#let the outputs be y i.e. the left most column

In [9]:
y
#just made to show the outputs

array([[5],
       [7],
       [9],
       ...,
       [2],
       [9],
       [5]])

In [10]:
x=np.delete(arr,0,1)

In [11]:
x
#this is the array of parameters/inputs resulting in outputs
#Just made to denote or show the inputs

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
Y=data.iloc[:,:1].values

In [13]:
X=data.iloc[:,1:].values

In [14]:
Y

array([[5],
       [7],
       [9],
       ...,
       [2],
       [9],
       [5]])

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [16]:
x_test.shape

(4000, 784)

In [17]:
x_train.shape

(15999, 784)

In [71]:
LR=LinearRegression()

In [66]:
LR.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
y_pred= LR.predict(x_test)

In [68]:
y_pred

array([[ 2.40974433],
       [ 6.26960928],
       [-0.19474285],
       ...,
       [ 5.0350772 ],
       [ 3.77124329],
       [-0.12968253]])