In [23]:
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data

In [26]:
data=pd.read_csv('/content/sample_data/mnist_train_small.csv')

In [27]:
print(data)

       6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0      5  0    0    0    0    0  ...      0      0      0      0      0      0
1      7  0    0    0    0    0  ...      0      0      0      0      0      0
2      9  0    0    0    0    0  ...      0      0      0      0      0      0
3      5  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
19994  0  0    0    0    0    0  ...      0      0      0      0      0      0
19995  1  0    0    0    0    0  ...      0      0      0      0      0      0
19996  2  0    0    0    0    0  ...      0      0      0      0      0      0
19997  9  0    0    0    0    0  ...      0      0      0      0      0      0
19998  5  0    0    0    0    0  ...      0      0      0      0      0      0

[19999 rows x 785 columns]


In [28]:
y=data.iloc[:,:1].values

In [29]:
y

array([[5],
       [7],
       [9],
       ...,
       [2],
       [9],
       [5]])

In [30]:
X=data.iloc[:,1:].values

In [31]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [32]:
m=X.shape[0] #number of independant variables
n=X.shape[1] #number of dependant variables

In [33]:
ones=np.ones((m,1))

In [34]:
X=np.concatenate((ones,X),axis=1)

In [35]:
X

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [36]:
def costfn_and_grad_descent(X,Y,alpha,max_iter):  #alpha is learning rate
   cost=np.zeros(max_iter)
   Theta=np.zeros(n+1) #initial theta vector
   h=np.dot(X, Theta) #hypothesis
   for i in range(0,max_iter):
      for j in range(0,n):
        Theta[j]=Theta[j]-(alpha/m)*(np.dot(sum(h-Y),X[:,j]))
      h=np.dot(X,Theta)
      cost[i]=(1/(2*m))*(np.sum(np.square((h-Y))))
   return cost, Theta


In [37]:
cost,Theta =costfn_and_grad_descent(X,y,0.01,10)

In [38]:
print(cost)

[4.50847506e+022 1.10483967e+040 2.70790705e+057 6.63695775e+074
 1.62668838e+092 3.98693977e+109 9.77180936e+126 2.39502635e+144
 5.87010145e+161 1.43873536e+179]


In [39]:
print(Theta)

[-1.47010103e+81  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -5.59455115e+77 -1.20842305e+79 -1.20842305e+79
 -5.03509604e+77  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.38957606e+79
 -3.38734852e+79 -7.20387082e+79 -8.57158262e+79 -1.82855150e+80
 -2.72395478e+80 -3.34324232e+80 -2.70939197e+80 -2.83366794e+80
 -2.63062124e+80 -2.12107453e+80 -2.43097833e+80 -2.44040543e+80
 -9.31499181e+79 -3.91133022e+79 -3.76534585e+78  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -2.36163811e+78 -2.06740